spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_news_system?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 000328
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: com_news_zxy
        group: news_work
      config:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  application:
    name: SpringNewsCommentService
logging:
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %blue([%-5level]) %cyan(%logger{36}:%line) %msg%n"
  level:
    tracer: trace
    sql: debug
    org:
      hibernate:
        SQL: debug
      springframework:
        cloud: debug
        web: debug
    com:
      site:
        springboot:
          core: debug
server:
  port: 28085


